apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streamlit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea-svc.default:3000/giteaadmin/helm.git
    targetRevision: main
    path: charts/streamlit
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: localhost:5000/streamlit
  destination:
    server: https://kubernetes.default.svc
    namespace: streamlit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # ignoreDifferences:
  #   - group: ""
  #     kind: Deployment
  #     jsonPointers:
  #       - /spec/template/spec/imagePullSecrets