- name: Deploy gitea from template manifest
  hosts: localhost
  connection: local

  vars_files:
    - ./vars/gitea_configmap.yaml

  vars:
    ModuleName: "gitea"
    Namespace: "default"
    PvPath: "./manifest/gitea_persistance.yaml"
    SvcPath: "./manifest/gitea_svc.yaml"
    DeployPath: "./manifest/gitea_deploy.yaml"

  tasks:
    - name: Deploy gitea ConfigMap
      template:
        src: ../../template/template_configmap.yaml.j2
        dest: /tmp/{{ ModuleName }}_cm.yaml 

    - name: Apply ALL manifest
      shell: |
        kubectl apply -f /tmp/{{ ModuleName }}_cm.yaml
      args:
        executable: /bin/bash
      register: apply_result
      failed_when: apply_result.rc != 0

    - name: Save apply 결과를 로컬 파일로 저장
      shell: |
        cp /tmp/{{ ModuleName }}_cm.yaml ./manifest/{{ ModuleName }}_cm.yaml
      when: apply_result.rc == 0

    - name: Apply PersistentVolume
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        src: "{{ PvPath }}"
        apply: true
        
    - name: Apply Svc
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        src: "{{ SvcPath }}"
        apply: true

    - name: Apply Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        src: "{{ DeployPath }}"
        apply: true
