apiVersion: v1
kind: ConfigMap
metadata:
  name: "airflow-env"
  namespace: "default"
data:
  AIRFLOW_HOME: "/opt/airflow"
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://admin:admin@postgres-svc.default:5432/airflow"
  AIRFLOW__CORE__HOSTNAME_CALLABLE: "airflow.utils.net:get_host_ip_address"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags/dags-main"
  AIRFLOW__CORE__DAG_DIR_LIST_INTERVAL: "10"
  AIRFLOW__CORE__DAG_IGNORE_FILE_SYNTAX_ERRORS: "True"
  AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://airflow-log"
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "minio_s3"
  AIRFLOW_CONN_MINIO_S3: "s3://minioadmin:minioadmin@minio-svc:9000?endpoint_url=http://minio-svc:9000"
  MINIO_ENDPOINT: "minio-svc:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  DATASOURCE_PATH: "postgresql+psycopg2://admin:admin@postgres-svc.default:5432/bi"
  AIRFLOW__CORE__PARALLELISM: "2"
  AIRFLOW__CORE__DAG_CONCURRENCY: "2"
  AIRFLOW__WEBSERVER__SECRET_KEY: "admin"
  AIRFLOW__METRICS__STATSD_ON: "False"
  AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_RECYCLE: "10"
  AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_TIMEOUT: "60"
  AIRFLOW__WEBSERVER__RBAC: "False"
  AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"
  PYTHONPATH: "/opt/airflow/dags/repo-main"
